---
- name: Install nginx
  yum: name=nginx state=present

- name: Ensure OpenSSL is installed
  yum: name=openssl state=present

- name: create ssl certs dir
  file: path=/etc/nginx/certs mode=755 state=directory owner=root

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=BY/ST=Minsk/L=Minsk/O=IT/CN={{ server_hostname }}" -days 3650 -keyout /etc/nginx/certs/server.key -out /etc/nginx/certs/server.crt -extensions v3_ca creates=/etc/nginx/certs/server.crt

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
