---
- name: Install proftpd
  yum: name=proftpd state=present

- name: Create user
  user:
    name=wp-user
    shell=/sbin/nologin
    home=/srv/wordpress/wp-content/uploads
    password=$6$saltsalt$TVLlQcbpFVof5W3Yz4DTP6gRstiNuHwwTt6GLc1E5n0U0aDehy0S5knV8wiOQSpT0Y77vwPZN.Pq.H91p5hVO1
    state=present

- name: Change permissions to session dir
  file:
    dest: /srv/wordpress/wp-content/uploads
    owner: wordpress
    group: wp-user
    mode: 0775
    recurse: true
  notify: restart proftpd

- name: Copy proftpd configuration for ftp
  template: src=proftpd.conf dest=/etc/proftpd.conf
  notify: restart proftpd
